on: push
name: Run tests
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@v1
      with:
        entrypoint: npm
        args: ci
    - name: Run test
      uses: actions/npm@v1
      with:
        entrypoint: npm
        args: run test
